on:
  workflow_run:
    workflows: ["simple test file"]
    types: [completed]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check test result
        run: |
         echo "Test workflow result: ${{ github.event.workflow_run.conclusion }}"

      - name: Deploy application
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo "Tests passed. Deploying application..."

      - name: Warn if tests failed
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: |
          echo "Tests failed. Deployment skipped."
          exit 1
