name: Docs Ignore Workflow

on:
  push:
    branches:
      - main
      - 'release/*'
    paths-ignore:
      - '*.md'
      - 'docs/**'

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Workflow ran because non-doc files changed"
